CREATE TABLE STUDENT(
	STUID INT,
	FIRSTNAME VARCHAR(25),
	LASTNAME VARCHAR(25),
	WEBSITE VARCHAR(50),
	CITY VARCHAR(25),
	ADDRESS VARCHAR(100)
);

SELECT *FROM STUDENT;

INSERT INTO STUDENT VALUES(1011,'Keyur','Patel','techonthenet.com','Rajkot','A-303 "Vasant Kunj" Rajkot');

INSERT INTO STUDENT VALUES (1022,'Hardik','Shah','digminecraft.com','Ahmedabad','“Ram Krupa”, Raiya Road');

INSERT INTO STUDENT VALUES (1033,'Kajal','Trivedi','bigactivities.com','Baroda','Raj bhavan plot, near
garden');

INSERT INTO STUDENT VALUES (1044,'Bhoomi','Gajera','checkyourmath.com','Ahmedabad','“Jig’s Home”, Narol ');

INSERT INTO STUDENT VALUES (1055,'Harmit','Mitel','@me.darshan.com','Rajkot','B-55, Raj Residency');

INSERT INTO STUDENT VALUES (1066,'Ashok','Jani',NULL,'Baroda','A502, Club House Building');

SELECT *FROM STUDENT;

SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE 'A%';

SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '_____';

SELECT FIRSTNAME,LASTNAME FROM STUDENT
WHERE CITY LIKE '_____a';

SELECT *FROM STUDENT
WHERE LASTNAME LIKE '%tel';

SELECT *FROM STUDENT
WHERE FIRSTNAME LIKE 'Ha%%t';

SELECT *FROM STUDENT
WHERE FIRSTNAME LIKE 'K_y%';

SELECT FIRSTNAME FROM STUDENT
WHERE WEBSITE IS NULL AND FIRSTNAME LIKE'_____';

SELECT LASTNAME FROM STUDENT
WHERE LASTNAME LIKE'%jer%'

SELECT CITY FROM STUDENT
WHERE CITY LIKE '[r,b]%';

SELECT FIRSTNAME FROM STUDENT
WHERE WEBSITE IS NOT NULL;

SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '[A-H]%';

SELECT LASTNAME FROM STUDENT
WHERE LASTNAME LIKE '_[A,E,I,O,U]%';

SELECT FIRSTNAME FROM STUDENT
WHERE WEBSITE IS NULL AND FIRSTNAME LIKE'_____';

SELECT LASTNAME FROM STUDENT
WHERE LASTNAME LIKE'Pat%';

SELECT CITY FROM STUDENT
WHERE CITY NOT LIKE 'B%';

SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '[A-H]%'

SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE 'H[A,E,I,O,U]%'

SELECT LASTNAME FROM STUDENT
WHERE LASTNAME NOT LIKE '%A'

SELECT LASTNAME FROM STUDENT
WHERE LASTNAME NOT LIKE '[A,E,I,O,U]%'

SELECT WEBSITE FROM STUDENT
WHERE WEBSITE LIKE '%.NET%'

SELECT ADDRESS FROM STUDENT
WHERE ADDRESS LIKE '%-%'

SELECT ADDRESS FROM STUDENT
WHERE ADDRESS LIKE '%['',""]%'

SELECT WEBSITE FROM STUDENT
WHERE WEBSITE LIKE '%@%'

SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '____ ' OR FIRSTNAME LIKE'_____'