CREATE TABLE EMP(
	EID INT,
	ENAME VARCHAR(50),
	DEPARTMANT VARCHAR(50),
	SALARY INT,
	JOININGDATE DATE,
	CITY VARCHAR(50)
);

SELECT *FROM EMP;

INSERT INTO EMP VALUES (101 ,'Rahul', 'Admin', 56000 ,'1-Jan-90', 'Rajkot');
INSERT INTO EMP VALUES (102 ,'Hardik' ,'IT' ,18000 ,'25-Sep-90' ,'Ahmedabad');
INSERT INTO EMP VALUES (103 ,'Bhavin' ,'HR' ,25000 ,'14-May-91' ,'Baroda');
INSERT INTO EMP VALUES (104 ,'Bhoomi' ,'Admin' ,39000, '8-Feb-91', 'Rajkot');
INSERT INTO EMP VALUES (105 ,'Rohit' ,'IT' ,17000 ,'23-Jul-90' ,'Jamnagar');
INSERT INTO EMP VALUES (106 ,'Priya' ,'IT' ,9000 ,'18-Oct-90', 'Ahmedabad');
INSERT INTO EMP VALUES (107 ,'Bhoomi' ,'HR' ,34000, '25-Dec-91', 'Rajkot');

SELECT MAX(SALARY) AS 'MAXIMUM_SALARY', MIN(SALARY) AS 'MINIMUM_SALARY'
FROM EMP;

SELECT SUM(SALARY) AS 'TOTAL_SALARY',AVG(SALARY) AS 'AVERAGE_SALARY'
FROM EMP;

SELECT COUNT(EID) AS 'TOTAL EMPLOYEE'
FROM EMP;

SELECT MAX(SALARY) AS 'MAX_SALARY'
FROM EMP
WHERE CITY='RAJKOT';

SELECT MAX(SALARY) AS 'MAX_SALARY'
FROM EMP
WHERE DEPARTMANT='IT';

SELECT COUNT(EID) AS 'A'
FROM EMP
WHERE JOININGDATE>'8-feb-91';

SELECT AVG(SALARY) AS 'AVG_SALARY'
FROM EMP
WHERE DEPARTMANT='ADMIN';

SELECT SUM(SALARY) AS 'AVG_SALARY'
FROM EMP
WHERE DEPARTMANT='HR';

SELECT COUNT(DISTINCT CITY) AS 'TOTAL_CITY'
FROM EMP;

SELECT COUNT(DISTINCT DEPARTMANT) AS 'CITY'
FROM EMP;

SELECT ENAME,MIN(SALARY) AS 'MIN'
FROM EMP
WHERE CITY='Ahmedabad';