--PART a
--1
ALTER TABLE DEPOSIT
ADD CITY VARCHAR(20),PINCODE INT
SELECT *FROM DEPOSIT

--2
ALTER TABLE DEPOSIT
ALTER COLUMN CNAME VARCHAR(35)
SELECT *FROM DEPOSIT 

--3
ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT
SELECT *FROM DEPOSIT

--4
SP_RENAME 'DEPOSIT.ACTNO', 'ANO', 'COLUMN'
SELECT *FROM DEPOSIT

--5
ALTER TABLE DEPOSIT
DROP COLUMN CITY
SELECT *FROM DEPOSIT

--6
SP_RENAME 'DEPOSIT','DEPOSITE_DETAIL'

--PART B
--1                                                                     
SP_RENAME 'DEPOSITE_DETAIL.ADATE','AOPENDATE','COLUMN'
SELECT *FROM DEPOSITE_DETAIL

--2
ALTER TABLE DEPOSITE_DETAIL
DROP COLUMN AOPENDATE
SELECT *FROM DEPOSITE_DETAIL

--3
SP_RENAME 'DEPOSITE_DETAIL.CNAME','CUSTOMERNAME','COLUMN'
SELECT *FROM DEPOSITE_DETAIL

--PART C
CREATE TABLE STUDENT_DETAIL(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(20),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)
--1
ALTER TABLE STUDENT_DETAIL
ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL
SELECT *FROM STUDENT_DETAIL

--2
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN NAME VARCHAR(35)
SELECT *FROM STUDENT_DETAIL 

--3
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT
SELECT *FROM STUDENT_DETAIL

--4
SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO','COLUMN'
SELECT *FROM STUDENT_DETAIL

--5
ALTER TABLE STUDENT_DETAIL
DROP COLUMN CITY
SELECT *FROM STUDENT_DETAIL

--6
SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'

--DELETE,TRUNCATE,DROP
--PART A
--1
DELETE FROM DEPOSITE_DETAIL
WHERE AMOUNT>=4000
SELECT *FROM DEPOSITE_DETAIL

--2
DELETE FROM DEPOSITE_DETAIL
WHERE BNAME='CHANDI'
SELECT *FROM DEPOSITE_DETAIL

--3
DELETE FROM DEPOSITE_DETAIL
WHERE ANO>105
SELECT *FROM DEPOSITE_DETAIL

--5
TRUNCATE TABLE DEPOSITE_DETAIL 
SELECT *FROM DEPOSITE_DETAIL

--6
DROP TABLE DEPOSITE_DETAIL
SELECT *FROM DEPOSITE_DETAIL

--PART B
CREATE TABLE EMPLOYEE_MASTER(
EMPNO INT,
EMPNAME VARCHAR(25),
JOININGDATE DATETIME,
SALARY DECIMAL(8,2),
CITY VARCHAR(20)
)

INSERT INTO EMPLOYEE_MASTER VALUES(101,'KEYUR','2002-1-5',12000,'RAJKOT')
INSERT INTO EMPLOYEE_MASTER VALUES(102,'HARDIK','2004-2-15',14000,'AHMEDABAD')
INSERT INTO EMPLOYEE_MASTER VALUES(103,'KAJAL','2006-3-14',15000,'BARODA')
INSERT INTO EMPLOYEE_MASTER VALUES(104,'BHOOMI','2005-6-23',12500,'AHMEDABAD')
INSERT INTO EMPLOYEE_MASTER VALUES(105,'HARMIT','2004-2-15',14000,'RAJKOT')
INSERT INTO EMPLOYEE_MASTER VALUES(106,'MITESH','2001-9-1',5000,'JAMNAGAR')
INSERT INTO EMPLOYEE_MASTER VALUES(107,'MEERA',NULL,7000,'MORBI')
INSERT INTO EMPLOYEE_MASTER VALUES(108,'KISHAN','2003-2-6',10000,NULL)
SELECT *FROM EMPLOYEE_MASTER

--1
DELETE FROM EMPLOYEE_MASTER
WHERE SALARY>14000
SELECT *FROM EMPLOYEE_MASTER

--2
DELETE FROM EMPLOYEE_MASTER
WHERE CITY='RAJKOT'
SELECT *FROM EMPLOYEE_MASTER

--3
DELETE FROM EMPLOYEE_MASTER
WHERE JOININGDATE>'2007-1-1'
SELECT *FROM EMPLOYEE_MASTER

--4
DELETE FROM EMPLOYEE_MASTER
WHERE JOININGDATE IS NULL AND EMPNAME IS NOT NULL
SELECT *FROM EMPLOYEE_MASTER

--5
DELETE FROM EMPLOYEE_MASTER
WHERE SALARY=10000
SELECT *FROM EMPLOYEE_MASTER

--6
DELETE FROM EMPLOYEE_MASTER
WHERE CITY IS NOT NULL
SELECT *FROM EMPLOYEE_MASTER

--7
TRUNCATE TABLE EMPLOYEE_MASTER

--8
DROP TABLE EMPLOYEE_MASTER;