CREATE TABLE CRICKET(
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	AGE INT
);

INSERT INTO CRICKET VALUES('Sachin Tendulkar','Mumbai',30);
INSERT INTO CRICKET VALUES('Rahul', 'Dravid Bombay' ,35);
INSERT INTO CRICKET VALUES('M. S. Dhoni' ,'Jharkhand' ,31);
INSERT INTO CRICKET VALUES('Suresh Raina' ,'Gujarat ',30);

SELECT *FROM CRICKET;

SELECT * INTO WORLDCUP2
FROM CRICKET 
WHERE 1=1;

SELECT *FROM WORLDCUP2;

SELECT NAME,CITY INTO T20
FROM CRICKET
WHERE 1=0;

SELECT *FROM T20;

SELECT *INTO IPL
FROM CRICKET
WHERE 1=0;

SELECT *FROM IPL;

CREATE TABLE EMPLOYEE(
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	AGE INT
);

INSERT INTO EMPLOYEE VALUES('Jay Patel', 'Rajkot' ,30);
INSERT INTO EMPLOYEE VALUES('Rahul Dave',' Baroda' ,35);
INSERT INTO EMPLOYEE VALUES('Jeet Patel' ,'Surat' ,31);
INSERT INTO EMPLOYEE VALUES('Vijay Raval' ,'Rajkot' ,30);

SELECT *FROM EMPLOYEE;

SELECT *INTO EMPLOYEE_DETAIL
FROM EMPLOYEE;

SELECT *FROM EMPLOYEE_DETAIL;

SELECT NAME,CITY INTO EMPLOYEE_DATA
FROM EMPLOYEE
WHERE 1=2;

SELECT *FROM EMPLOYEE_DATA;

SELECT *INTO EMPLOYEE_INFO
FROM EMPLOYEE
WHERE 1=0;

SELECT *FROM EMPLOYEE_INFO;

INSERT INTO EMPLOYEE_INFO
SELECT *FROM EMPLOYEE
WHERE CITY='RAJKOT';

SELECT *FROM EMPLOYEE_INFO;

INSERT INTO EMPLOYEE_INFO
SELECT *FROM EMPLOYEE
WHERE AGE>32;

SELECT *FROM EMPLOYEE_INFO;

UPDATE DEPOSIT
SET AMOUNT=5000
WHERE AMOUNT=3000;

SELECT *FROM DEPOSIT;

SELECT *FROM BORROW;

UPDATE BORROW
SET CITY='C.G. ROAD'
WHERE CITY='VRCE' AND CNAME='ANIL'

SELECT *FROM BORROW;

SELECT *FROM DEPOSIT
UPDATE DEPOSIT
SET ACTNO=111 , AMOUNT=5000
WHERE CNAME='SANDIP';

SELECT *FROM DEPOSIT

UPDATE DEPOSIT
SET AMOUNT=7000
WHERE CNAME='KRANTI'

SELECT *FROM DEPOSIT;

UPDATE BRANCH
SET BNAME='ANDHERI WEST'
WHERE BNAME='ANDHERI'
SELECT *FROM BRANCH;

UPDATE DEPOSIT
SET BNAME='NEHRU PALACE'
WHERE CNAME='MEHUL';
SELECT *FROM DEPOSIT;

UPDATE DEPOSIT
SET AMOUNT=5000
WHERE ACTNO BETWEEN 103 AND 107; 
SELECT *FROM DEPOSIT;

UPDATE DEPOSIT
SET ADATE='1-4-95'
WHERE CNAME='ANIL'
SELECT *FROM DEPOSIT;

UPDATE DEPOSIT
SET AMOUNT=10000
WHERE CNAME='MINU'
SELECT *FROM DEPOSIT;

UPDATE DEPOSIT
SET ADATE='1-4-96' ,AMOUNT=5000
WHERE CNAME='PRAMOD'
SELECT *FROM DEPOSIT;

UPDATE BORROW
SET AMOUNT=AMOUNT+(AMOUNT)*0.10
SELECT *FROM BORROW;

UPDATE DEPOSIT
SET AMOUNT=AMOUNT+(AMOUNT)*0.20
SELECT *FROM DEPOSIT;

UPDATE BORROW
SET LOANNO=NULL
WHERE LOANNO=321
SELECT *FROM BORROW;

UPDATE BORROW
SET CITY=NULL
WHERE CNAME='KRANTI'
SELECT *FROM BORROW;

SELECT *FROM BORROW
WHERE AMOUNT IS NULL;

SELECT *FROM BORROW
WHERE CITY IS NOT NULL

UPDATE BORROW
SET AMOUNT=5000, CNAME='DARSHAN',CITY='VRCE'
WHERE LOANNO=481
SELECT *FROM BORROW;

UPDATE DEPOSIT
SET ADATE='01-01-2021'
WHERE AMOUNT<2000
SELECT *FROM DEPOSIT;

UPDATE DEPOSIT
SET BNAME='ANDHERI',ADATE=NULL
WHERE ACTNO<110
SELECT *FROM DEPOSIT;

